# Generated by Django 4.2.5 on 2023-09-26 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile.jpeg', upload_to='photos/users', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
