# Generated by Django 4.2 on 2023-09-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_userprofile_image"),
        ("account", "0002_userprofile_cart"),
    ]

    operations = []
