# Generated by Django 4.2 on 2023-11-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_commentreply_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="category/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="amount_in_stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="likes",
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
