# Generated by Django 4.2 on 2023-11-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_category_image_alter_product_amount_in_stock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
