# Generated by Django 4.2 on 2023-08-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_product_discount_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
    ]
