# Generated by Django 4.2 on 2023-11-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_product_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vendor_price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
