# Generated by Django 4.2 on 2023-11-15 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_product_vendor_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="colors",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sizes",
        ),
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_in_stock", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.sizeoption",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_in_stock", models.BooleanField(default=True)),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.coloroption",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="new_colors",
            field=models.ManyToManyField(
                related_name="new_product_colors",
                through="product.ProductColor",
                to="product.coloroption",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="new_sizes",
            field=models.ManyToManyField(
                related_name="new_product_sizes",
                through="product.ProductSize",
                to="product.sizeoption",
            ),
        ),
    ]
