# Generated by Django 4.2 on 2023-08-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_product_likes_productcomment_commentreply"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentreply",
            name="is_vendor_comment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productcomment",
            name="is_vendor_comment",
            field=models.BooleanField(default=False),
        ),
    ]
