# Generated by Django 4.2 on 2023-11-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_remove_product_new_colors_remove_product_new_sizes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
