# Generated by Django 4.2 on 2023-09-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="amount_stock",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
