# Generated by Django 4.2 on 2023-09-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_recentlyviewed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="amount_stock",
            new_name="amount_in_stock",
        ),
    ]
