# Generated by Django 4.2 on 2023-10-17 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card", models.BooleanField(default=False)),
                ("momo", models.BooleanField(default=False)),
                ("card_number", models.CharField(blank=True, max_length=50, null=True)),
                ("card_exp", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "card_type",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Visa Card"),
                            (1, "Mastercard"),
                            (2, "Gh-Link"),
                            (3, "Other"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "momo_type",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "MTN"),
                            (1, "Vodafone"),
                            (2, "Airtel-Tigo"),
                            (3, "Other"),
                        ],
                        null=True,
                    ),
                ),
                ("momo_number", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=225, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=100, null=True
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=225, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid", models.BooleanField(default=False)),
                ("shipped", models.BooleanField(default=False)),
                ("route", models.BooleanField(default=False)),
                ("delivered", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendors",
                    models.ManyToManyField(
                        blank=True, related_name="orders", to="vendors.vendor"
                    ),
                ),
            ],
        ),
    ]
