# Generated by Django 4.2 on 2023-10-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_savedpayment_card_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedpayment",
            name="card_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Visa Card"),
                    (1, "Mastercard"),
                    (2, "Gh-Link"),
                    (3, "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="savedpayment",
            name="momo_type",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "MTN"), (1, "Vodafone"), (2, "Airtel-Tigo"), (3, "Other")],
                null=True,
            ),
        ),
    ]
