# Generated by Django 4.2 on 2023-10-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_savedpayment_card_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=100, null=True
            ),
        ),
    ]
