# Generated by Django 4.2 on 2023-10-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_message_chat_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
