# Generated by Django 4.2 on 2023-11-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0015_alter_vendor_pin"),
        ("accounts", "0005_remove_user_code_user_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="promo_code",
            field=models.ManyToManyField(blank=True, to="vendors.promo_code"),
        ),
    ]
