# Generated by Django 4.2 on 2023-11-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_promo_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="pin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="promo_code",
        ),
        migrations.AddField(
            model_name="user",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
