# Generated by Django 4.2 on 2023-11-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0015_alter_vendor_pin"),
        ("accounts", "0007_remove_user_pin_remove_user_promo_code_user_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="promo_code",
            field=models.ManyToManyField(blank=True, to="vendors.promo_code"),
        ),
    ]
