# Generated by Django 4.2 on 2023-11-10 23:51

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0010_vendoractivehours"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendoractivehours",
            options={"verbose_name_plural": "Vendor Active Hours"},
        ),
        migrations.AlterField(
            model_name="vendor",
            name="pin",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=5)),
        ),
    ]
