# Generated by Django 4.2 on 2023-11-11 00:00

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0014_alter_vendor_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="pin",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=5)),
        ),
    ]
